### ISSUE TITLE
Bug in clone()

### ISSUE THREAD

**Issue by kripper** [DEVSENSE/Phalanger#28]
This test-case shows 'A is wrong' instead of 'A is ok':

```
$a = new stdClass();
$a->test = 'ok';
$ptr = & $a->test; // <--- This reference corrupts $a's clonation
$b = clone($a);
$b->test = "wrong";
die('A is ' . $a->test);
```

Note that even doing unset($ptr) doesn't workarround the bug:

```
$ptr = & $a->test; // This reference corrupts $a's clonation
unset($ptr);
```

**Comment by kripper** [comment]
Has this been fixed in PeachPie?

**Comment by jakubmisek** [comment]
@kripper running the sample on `PHP 7.1` gives me:
`A is wrong`

**Comment by kripper** [comment]
Hi @jakubmisek, you are right. PHP 7.1's has the same bug:

```
$orig = new stdClass();
$orig->test = 'original';

$ptr = & $orig->test; // <--- Setting a ptr changes the behaviour 

$copy = clone $orig;
$copy->test = "modified";

die("Orig is: {$orig->test}"); // Gives 'modified'
```

But, if you unset $ptr, Phalanger's behaviour is different than PHP 7.1's:

```
$orig = new stdClass();
$orig->test = 'original';

$ptr = & $orig->test;
unset($ptr); // <--- This fixes the problem

$copy = clone $orig;
$copy->test = "modified";

die("Orig is: {$orig->test}"); // PHP 7.1 gives 'original', but Phalanger gives 'modified'
```

**Comment by jakubmisek** [comment]
@kripper I wouldn't call it bug - `clone` to a reference behaves correctly - the test is wrong

edit: until it behaves like in PHP, it is correct .. since it is not defined well in PHP, we can't specify the correct behavior either

**Comment by jakubmisek** [comment]
@kripper `unset` clears the reference (decreases refs count) which is not possible with .NET GC.

**Comment by kripper** [comment]
I consider it a bug because setting an unused reference shouldn't change the behavior of "clone".
Do you know any workaround for using references to object properties and still be able to clone objects?

**Comment by jakubmisek** [comment]
by contraries; making a variable reference changes behavior. That's the purpose of refs. So it seams in PHP 7 the behavior was fixed:
`clone ref => ref`
`clone val => copy of val`

**Comment by kripper** [comment]
Sorry, I don't understand your comment.
In the example, `$ptr` is a reference to `$orig->test`.

$orig->test **is not** a reference to $ptr and we are not cloning a reference, but a object that **is being** referenced by $ptr.

Anyway, after doing `$ptr = & $orig->test`, PHP seems to treat `$orig->test` as a reference, and like you said (clone ref => ref), the result is that `$ptr`, `$orig->test` and `$cloned->test` are all references to the same value.

If it's not a bug, It's a pity that PHP changed how this works since v5.6, because now I see no way how to use cloned objects together with references, and it's impossible to migrate working code.

I believe this is a design problem that has and will be discussed until fixed, probably related to the fact that PHP probably only manages variable aliases tables instead of real references in only one direction (where $a references $b and $b does not reference $a).

**Comment by kripper** [comment]
Closing.
This is a language design problem in PHP, not a problem with Phalanger.
See more info here: https://bugs.php.net/bug.php?id=75632
