### ISSUE TITLE
"import" as function name throws error when compiling php to dll in strict mode even though it isn't a reserved word in php or c#

### ISSUE THREAD

**Issue by robertleeplummerjr** [DEVSENSE/Phalanger#49]
I tried with latest from github.  I can see the issue in the lexer and parser, but not sure how to best solve it.  The options are to create a lookahead rule & token in the lexer, or perhaps to provide another parser match that accepts that as an acceptable combination.

**Comment by robertleeplummerjr** [comment]
Error: ............\GitHub\redbean\RedBeanPHP\OODBBean.php(423,18): error PHP2014: Syntax error: unexpected token 'import'

Parsing this file: https://github.com/gabordemooij/redbean/blob/master/RedBeanPHP/OODBBean.php#L423

**Comment by jakubmisek** [comment]
"import" is a keyword in Phalanger Pure mode. It is deprecated and will be removed in a future version.

**Comment by robertleeplummerjr** [comment]
Can I assist?  What is the plan moving forward?

On Sun, Apr 5, 2015 at 10:56 AM, Jakub Míšek <notifications@github.com>
wrote:

> Closed #49 <https://github.com/DEVSENSE/Phalanger/issues/49>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DEVSENSE/Phalanger/issues/49#event-273625790>.
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
Also, thanks for your speedy reply.

On Sun, Apr 5, 2015 at 12:27 PM, Robert Plummer <
robertleeplummerjr@gmail.com> wrote:

> Can I assist?  What is the plan moving forward?
>
> On Sun, Apr 5, 2015 at 10:56 AM, Jakub Míšek <notifications@github.com>
> wrote:
>
>> Closed #49 <https://github.com/DEVSENSE/Phalanger/issues/49>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/DEVSENSE/Phalanger/issues/49#event-273625790>.
>>
>
>
>
> --
> Robert Plummer
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
I went ahead and pull requested with import removed, and here is what we were able to achieve: https://github.com/robertleeplummerjr/redbean.net

**Comment by jakubmisek** [comment]
Very nice!

**Comment by robertleeplummerjr** [comment]
I love how you've implemented your own ebnf parser.  You guys are wicked
smart.  I ported one (https://github.com/Bovid) but never had the gumption
to start from scratch.

On Tue, Apr 7, 2015 at 12:35 PM, Jakub Míšek <notifications@github.com>
wrote:

> Very nice!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DEVSENSE/Phalanger/issues/49#issuecomment-90638648>.
>



-- 
Robert Plummer
