### ISSUE TITLE
problems with .net 4.6

### ISSUE THREAD

**Issue by proff** [DEVSENSE/Phalanger#53]
in .net 4.6 anonymous delegates compiles as instance methods even if target is 4.5 and this code is not working:
```
            Func<object,object> isNotPhpReference = (obj) =>
            {
               Debug.Assert( !(obj is PhpReference) );
               return obj;
            };

            return Expression.Call(null, isNotPhpReference.Method, objEx);
```
must use static mehods
```
        private static object IsNotPhpReference(object obj)
        {
            Debug.Assert(!(obj is PhpReference));
            return obj;
        }
```

**Comment by jakubmisek** [comment]
fixed as suggested

**Comment by proff** [comment]
In my branch it was not the only one anonymous delegate with this problem, but I worked with old branch. Fix like this must applyed to all delegates called via "Expression.Call(null..."

**Comment by jakubmisek** [comment]
thanks, fixed
