### ISSUE TITLE
Generic version with returned value of TreeVisitor

### ISSUE THREAD

**Issue by KvanTTT** [DEVSENSE/Phalanger#54]
It will be good to support TreeVisitor<AstNode> for convenient php AST conversion in custom format.
Roslyn and ANTLR does support it.

**Comment by bfistein** [comment]
@KvanTTT Phalanger's development is mostly discontinued in favor of [PeachPie](https://github.com/peachpiecompiler/peachpie), the more modern compiler and runtime that also targets .NET Core. Please feel free to give that a try.

**Comment by KvanTTT** [comment]
Yes, thank you, I know it :)
