### ISSUE TITLE
How to add Phalanger to ASP.NET MVC Project?

### ISSUE THREAD

**Issue by AdwardNguyen** [DEVSENSE/Phalanger#83]
I read this topic and i just download Phalanger latest version.
I have an error when build my project using responsive file manager with TinyCME editor
![1111](https://user-images.githubusercontent.com/22392606/32564592-4e4fac16-c4e7-11e7-8c3d-998734e7c919.PNG)
![2222](https://user-images.githubusercontent.com/22392606/32564593-4e7fb244-c4e7-11e7-9b4c-58c88d69223e.PNG)
![3333](https://user-images.githubusercontent.com/22392606/32564595-4f4452fc-c4e7-11e7-8c85-1389268ea70f.PNG)
![4444](https://user-images.githubusercontent.com/22392606/32564596-4f794778-c4e7-11e7-8686-452679897677.PNG)

**Comment by jakubmisek** [comment]
What was the issue?
